### ISSUE TITLE
The POST method is not supported for route builder/login. Supported methods: GET, HEAD.

### ISSUE THREAD

**Issue by PavaMarja** [LaravelDaily/FilaStart#10]
Hello, I gitclone project and change only type of database se mysql and credidentials for database. Everything goes ok until click on submit on log on screen. Then there is error "The POST method is not supported for route builder/login. Supported methods: GET, HEAD.". The same error got when try to register. I use user name and password from page.
![image](https://github.com/LaravelDaily/FilaStart/assets/48047684/449aba80-ffaf-40ed-8c9b-7ae0a83d5e36)

Can you help me ?  

Pavao Marjanović

**Comment by ModestasV** [comment]
Do a `composer update` as there might be a bug somewhere

**Comment by PavaMarja** [comment]
I did with composer update , but the same. Also try with php artisan optimize. No help.
![image](https://github.com/LaravelDaily/FilaStart/assets/48047684/fba475e3-628e-4d96-bdbe-c0d124226b72)

**Comment by ModestasV** [comment]
I'm not sure about what can be happening there. Downloaded a fresh copy and did not see this problem. What I see right now in your URL is the fact that you placed this into a sub-folder. So your issues might be there.

Unfortunately, this is out of the scope of this system's use case, so I must close this issue. 

I recommend using this tool locally instead of on a server and in a sub-folder.

**Comment by PavaMarja** [comment]
Thank you...I will try to install as I did with other Laravel project..Not in subfolder.
