### ISSUE TITLE
Disable Softdelete

### ISSUE THREAD

**Issue by shasan-dev** [LaravelDaily/FilaStart#13]
While creating crud, even if I delete deleted at, it doesn't delete the $table - > softdeletes() in the code generated.

**Comment by ModestasV** [comment]
This is because it is not built-in and was left as a potential future update.

You can fork this project and add a condition here:
https://github.com/LaravelDaily/FilaStart/blob/main/systems/generators/laravel11/src/Generators/MigrationGenerator.php#L103


Currently this project did not get enough traction and we did not plan to push any updates for now :)
